---
apiVersion: v1
kind: Namespace
metadata:
  name: ran-httpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-httpd-app-deployment
  namespace: ran-httpd
  labels: 
    app: ran-httpd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ran-httpd-app
  template:
    metadata:
      labels:
        app: ran-httpd-app
    spec:
      containers:
      - name: ran-httpd-container
        image: my-httpd-app:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ran-httpd-service
  namespace: ran-httpd
  labels:
    app: ran-httpd-app
spec:
  type: NodePort
  selector:
    app: ran-httpd-app
  ports:
    - nodePort: 30010
      protocol: TCP
      port: 80
      targetPort: 80
---
